GMAIL_USERNAME: ianrtracey@gmail.com
GMAIL_PASSWORD: Filly901doublesecure

SENDGRID_USERNAME: devi-hackarizona
SENDGRID_PASSWORD: muskyHacks145^q1
TYPEFORM_URI: 'https://api.typeform.com/v0/form/C7QX2g?key=666784358a96968db6fe9195aaf3fc63571540c0&completed=true'